project_id = "mjqykgcvfteihqmgeufb"

[functions.french-tts]
verify_jwt = false

[functions.transcribe-pronunciation]
verify_jwt = false

[functions.analyze-fluency]
verify_jwt = false

[functions.analyze-skill]
verify_jwt = false
